openapi: 3.0.0
info:
  description: You can get all events of a case or application including timestamp, actors, type, link to documents and many more.
  version: 2.0.0
  title: Ereignisse API
  contact:
    name: Europace AG
    url: 'https://docs.api.europace.de/baufinanzierung/ereignisse_vorg/'
    email: helpdesk@europace2.de
tags:
  - name: events of case
    description: all events for advisor
  - name: events of application
    description: all events for loan officer
paths:
  /ereignisse:
    get:
      tags:
        - events of case
      summary: get events for case
      description: 'As advisor you can get all events of case to get an overview for the last actions.'
      operationId: getEreignisseByVorgang
      parameters:
        - name: vorgangsNummer
          in: query
          description: case-id
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json;charset=UTF-8:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Ereignis'
        '401':
          description: |-
            Unauthorized
            no valid token
          content:
            application/json;charset=UTF-8:
              schema:
                $ref: '#/components/schemas/Error'
        '403':
          description: |-
            Forbidden
            Insufficient access rights
          content:
            application/json;charset=UTF-8:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: |-
            Not Found
          content:
            application/json;charset=UTF-8:
              schema:
                $ref: '#/components/schemas/Error'
        '405':
          description: Method Not Allowed
          content:
            application/json;charset=UTF-8:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal Server Error
          content:
            application/json;charset=UTF-8:
              schema:
                $ref: '#/components/schemas/Error'
        '502':
          description: |-
            Bad Gateway
          content:
            application/json;charset=UTF-8:
              schema:
                $ref: '#/components/schemas/Error'
        '503':
          description: |-
            Service Unavailable
          content:
            application/json;charset=UTF-8:
              schema:
                $ref: '#/components/schemas/Error'
        '504':
          description: Gateway Timeout
          content:
            application/json;charset=UTF-8:
              schema:
                $ref: '#/components/schemas/Error'
      security:
        - oauth2:
            - 'baufinanzierung:ereignis:lesen'
            - 'baufinanzierung:echtgeschaeft'
            - 'partner:plakette:lesen'
            - 'unterlagen:dokument:lesen'
  '/ereignisse/{vorgangsNummer}':
    get:
      tags:
        - events of case
      summary: get events of case
      description: 'As advisor you can get all events of case to get an overview for the last actions.'
      operationId: getEreignisse
      parameters:
        - name: vorgangsNummer
          in: path
          description: case-id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json;charset=UTF-8:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Ereignis'
        '401':
          description: |-
            Unauthorized
            no valid token
          content:
            application/json;charset=UTF-8:
              schema:
                $ref: '#/components/schemas/Error'
        '403':
          description: |-
            Forbidden
          content:
            application/json;charset=UTF-8:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: |-
            Not Found
          content:
            application/json;charset=UTF-8:
              schema:
                $ref: '#/components/schemas/Error'
        '405':
          description: Method Not Allowed
          content:
            application/json;charset=UTF-8:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal Server Error
          content:
            application/json;charset=UTF-8:
              schema:
                $ref: '#/components/schemas/Error'
        '502':
          description: Bad Gateway
          content:
            application/json;charset=UTF-8:
              schema:
                $ref: '#/components/schemas/Error'
        '503':
          description: |-
            Service Unavailable
          content:
            application/json;charset=UTF-8:
              schema:
                $ref: '#/components/schemas/Error'
        '504':
          description: Gateway Timeout
          content:
            application/json;charset=UTF-8:
              schema:
                $ref: '#/components/schemas/Error'
      security:
        - oauth2:
            - 'baufinanzierung:ereignis:lesen'
            - 'baufinanzierung:echtgeschaeft'
            - 'partner:plakette:lesen'
            - 'unterlagen:dokument:lesen'
  '/ereignisse/{vorgangsNummer}/{antragsNummer}/{teilAntragsNummer}':
    get:
      tags:
        - events of application
      summary: get events of application
      description: 'As loan officer you can get all events of application to get an overview for the last actions.'
      operationId: getAntragsEreignisse
      parameters:
        - name: vorgangsNummer
          in: path
          description: case-id
          required: true
          schema:
            type: string
        - name: antragsNummer
          in: path
          description: iteratorSolution
          required: true
          schema:
            type: string
        - name: teilAntragsNummer
          in: path
          description: iteratorApplication
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json;charset=UTF-8:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Ereignis'
        '401':
          description: |-
            Unauthorized
          content:
            application/json;charset=UTF-8:
              schema:
                $ref: '#/components/schemas/Error'
        '403':
          description: |-
            Forbidden
          content:
            application/json;charset=UTF-8:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: |-
            Not Found
          content:
            application/json;charset=UTF-8:
              schema:
                $ref: '#/components/schemas/Error'
        '405':
          description: Method Not Allowed
          content:
            application/json;charset=UTF-8:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal Server Error
          content:
            application/json;charset=UTF-8:
              schema:
                $ref: '#/components/schemas/Error'
        '502':
          description: Bad Gateway
          content:
            application/json;charset=UTF-8:
              schema:
                $ref: '#/components/schemas/Error'
        '503':
          description: |-
            Service Unavailable
          content:
            application/json;charset=UTF-8:
              schema:
                $ref: '#/components/schemas/Error'
        '504':
          description: Gateway Timeout
          content:
            application/json;charset=UTF-8:
              schema:
                $ref: '#/components/schemas/Error'
      security:
        - oauth2:
            - 'baufinanzierung:ereignis:lesen'
            - 'baufinanzierung:echtgeschaeft'
            - 'partner:plakette:lesen'
            - 'unterlagen:dokument:lesen'
servers:
  - url: 'https://baufismart.api.europace.de/v2'
components:
  securitySchemes:
    oauth2:
      type: oauth2
      flows:
        clientCredentials:
          scopes:
            'baufinanzierung:ereignis:lesen': 'to get event information'
            'baufinanzierung:echtgeschaeft': 'to use api in production mode'
            'partner:plakette:lesen': 'to get partner information'
            'unterlagen:dokument:lesen': 'to get documents'
          tokenUrl: 'https://api.europace.de/auth/token'
  schemas:
    Partner:
      type: object
      properties:
        partnerId:
          type: string
          description: Europace partner identifier
        anrede:
          type: string
          description: salutation
          enum:
            - FRAU
            - HERR
        nachname:
          type: string
          description: surname
        vorname:
          type: string
          description: first name
        externePartnerId:
          type: string
          description: own partner reference
      title: Partner
      description: actor of event
    Ereignis:
      type: object
      properties:
        vorgangsNummer:
          type: string
          description: case-id
        antragsNummer:
          type: string
          description: application-id
        meldung:
          type: string
          description: message text
        typ:
          type: string
          description: |
            event type. 
            Type 'STATUS_AENDERUNG' is related to the following changes on the case:
                       * offer accepted
                       * approved offer not accepted
                       * own case reference set
                       * editor set
                       * advisor set
                       * tipster set
                       * date of estimated approval set
                       * counteroffer created
                       * state has changed
            If type 'DOKUMENTE', the element 'dokumente' will be present. 
            If type 'ANTRAGSTATUS_AENDERUNG' the element 'antragsStatus' will be present.
          enum:
            - DOKUMENTE
            - STATUS_AENDERUNG
            - WIEDERVORLAGE
            - KOMMENTAR
            - KOMMUNIKATION
            - HINWEIS
            - EXPORT
        zeitpunkt:
          type: string
          format: date-time
          description: timestamp of event
        quelle:
          $ref: '#/components/schemas/Partner'
          description: actor of event
        dokumente:
          type: array
          items:
            $ref: '#/components/schemas/Dokumente'
        antragsStatus:
          $ref: '#/components/schemas/AntragsStatus'
      title: Ereignis
      x-examples:
        example-1:
          vorgangsNummer: string
          antragsNummer: string
          meldung: string
          typ: DOKUMENTE
          zeitpunkt: '2019-08-24T14:15:22Z'
          quelle:
            partnerId: string
            anrede: FRAU
            nachname: string
            vorname: string
            externePartnerId: string
          dokumente:
            - name: string
              geloescht: true
              _links:
                self:
                  href: 'http://example.com'
                  type: string
                download:
                  href: 'http://example.com'
                  type: string
                publicDownload:
                  href: 'http://example.com'
                  type: string
          antragsStatus:
            antragsteller: BEANTRAGT
            produktAnbieter: NICHT_BEARBEITET
            kommentar: string
            ablehnungsgrund: FINANZIELLE_SITUATION
            bearbeitungsFortschritt: NICHT_VON_PRODUKTANBIETER_BESTAETIGT
    Dokumente:
      type: object
      properties:
        name:
          type: string
          description: document name
        geloescht:
          type: boolean
          description: |
            If a document has been deleted according to GDPR guidelines, then the value is set to true. In this case, no links are output. For non-deleted documents, this value is not set.
        _links:
          $ref: '#/components/schemas/DokumentenLink'
    DokumentenLink:
      type: object
      properties:
        self:
          $ref: '#/components/schemas/Relation'
        download:
          $ref: '#/components/schemas/Relation'
          description: internal download url
        publicDownload:
          $ref: '#/components/schemas/Relation'
          description: public download url
    Relation:
      type: object
      properties:
        href:
          type: string
          format: uri
          description: link to ressource
        type:
          type: string
          description: 'media-type according to https://tools.ietf.org/html/rfc6838.'
    Error:
      type: object
      properties:
        message:
          type: string
        statusCode:
          type: integer
          format: int32
        statusMessage:
          type: string
        timestamp:
          type: string
        traceId:
          type: string
      title: Error
    AntragsStatus:
      type: object
      description: state of application
      properties:
        antragsteller:
          $ref: '#/components/schemas/AntragstellerStatus'
        produktAnbieter:
          $ref: '#/components/schemas/ProduktAnbieterStatus'
        kommentar:
          type: string
        ablehnungsgrund:
          type: string
          description: reason for rejection
          enum:
            - FINANZIELLE_SITUATION
            - NEGATIV_MERKMAL
            - WERTERMITTLUNG
            - KRITERIEN
            - UNTERLAGEN_UNVOLLSTAENDIG
            - GEGENANGEBOT
            - KEINE_ANGABE
        bearbeitungsFortschritt:
          type: string
          description: application progress after signing by both parties
          enum:
            - NICHT_VON_PRODUKTANBIETER_BESTAETIGT
            - VON_PRODUKTANBIETER_BESTAETIGT
            - FREIGEGEBEN_FUER_SAMMELFORDERUNG
            - PROVISION_IN_BEARBEITUNG
            - PROVISON_AN_KUNDENBETREUER_VOLLSTAENDIG_AUSGEZAHLT
    ProduktAnbieterStatus:
      type: string
      description: state of loan provider
      enum:
        - NICHT_BEARBEITET
        - UNTERSCHRIEBEN
        - ABGELEHNT
        - ZURUECKGESTELLT
    AntragstellerStatus:
      type: string
      description: state of customer
      enum:
        - BEANTRAGT
        - UNTERSCHRIEBEN
        - NICHT_ANGENOMMEN
        - WIDERRUFEN
